In [27]:
##Task 1
import numpy as np 

result = np.array([[1, 2], [3, 4]]) 
print(result *2 + 1)

[[3 5]
 [7 9]]


In [28]:
##Task 2

first = np.array([2,4])
second= np.array([6,8])

result = np.array([first,second])
print(result)

result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [9]:
##Task 3
first = np.array([1,2])
second= np.array([3,4])

result = np.array([first,second])
print(result**2)

[[ 1  4]
 [ 9 16]]


In [22]:
##Task 4
## аналитическое нормирование 
norm1 = np.linalg.norm(np.array([1, 2, 3, 4]))
nparray2 = np.array([[1, 2], [3, 4]]) 
norm2 = np.linalg.norm(nparray2)

print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


In [11]:
##Task 5
nparray = np.array([[1, 1], [2, 2], [3, 3]])

normByCols = np.linalg.norm(nparray, axis = 0) 
normByRows = np.linalg.norm(nparray, axis = 1)

print(normByCols)
print(normByRows)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [12]:
##Task 6
nparray1 = np.array([0, 1, 2, 3]) 
nparray2 = np.array([4, 5, 6, 7]) 

flavor1 = np.dot(nparray1,nparray2)
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2)
print(flavor2)

flavor3 = nparray1 @ nparray2         
print(flavor3)


flavor4 = 0
for a, b in zip(nparray1, nparray2):
    flavor4 += a*b
    
print(flavor4)

38
38
38
38


In [13]:
##Task 7
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])

sumByCols = np.sum(nparray2, axis = 0) 
sumByRows = np.sum(nparray2, axis = 1)  
 
print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


In [14]:
##Task 8
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) 


mean = np.mean(nparray2)    
meanByCols =np.mean(nparray2, axis = 0)   
meanByRows = np.mean(nparray2, axis = 1)    
 
print('Matrix mean: ')
print(mean) 
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows) 

Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


In [15]:
##Task 9
nparray2 = np.array([[1, 1], [2, 2], [3, 3]])

nparrayCentered = nparray2 - np.mean(nparray2, axis = 0) 


print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))


Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


In [16]:
##Task 10
nparray2 = np.array([[1 ,3], [2 ,4], [3 ,5]]) 
nparrayCentered = nparray2 - np.mean(nparray2, axis=1, keepdims = True)
nparrayCentered = nparrayCentered.T 

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered.T)

print('New mean by rows')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]
