In [13]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [63]:
betta=1
ro=0.5

FV=[]
FV.append(fv1)
FV.append(fv2)
FV.append(fv3)
fv1 =np.array([1,0,0,1,1,1,0,0,1])
fv2 =np.array([1,0,0,1,1,1,0,1,1])
fv3 =np.array([1,1,1,1,1,1,0,0,1])


P=[] 
pv1=np.array([0,1,1,0,1,0,0,1,0])
pv2=np.array([1,1,1,0,0,0,1,1,1])
pv3=np.array([1,0,0,1,1,0,0,0,0])
P.append(pv1)
P.append(pv2)
P.append(pv3)

In [64]:
def similarity(fv,pv,betta):
    n=P[0].shape[0]
    left=np.sum(fv*pv)/(betta+np.sum(pv))
    rigth=np.sum(fv)/(betta+n)     
    return left>rigth
print(similarity(fv1,P[2],betta))

True


In [65]:
def vigilance(fv,pv,ro):
    left=np.sum(fv*pv)/np.sum(fv)
    return left>ro
print(vigilance(fv1,P[2],ro))

True


In [66]:
def selectCluster(P,fv,betta,ro):
    numberOfHostCluster=None
    i = 0
    change=False
    for p in P:
        i+=1
        if similarity(fv,p,betta) and vigilance(fv,p,ro):
            print('True')
            print(i)
            HostCluster =p
            change=False
        else:
            print('False')
            change=True
            HostCluster=fv
    if change:
        np.append(P, HostCluster)
        print(i)
    
    return P, HostCluster, i, change
P,HostCluster,number, check=selectCluster(P,fv1,betta,ro)
print('P=',P)
print('HostCluster=',HostCluster)
print('number=',number)

False
False
True
3
P= [array([0, 1, 1, 0, 1, 0, 0, 1, 0]), array([1, 1, 1, 0, 0, 0, 1, 1, 1]), array([1, 0, 0, 1, 1, 0, 0, 0, 0])]
HostCluster= [1 0 0 1 1 0 0 0 0]
number= 3


In [67]:
#Ваши задачи таковы
#обновить кластер и написать cicle для всех векторов объектов

In [68]:
# Task1
def renewCluster(fv,pv):
    for i in range(len(pv)):
        pv[i] = pv[i] * fv[i]
#         print('{0}*{1}={2}'.format(pv[i], fv[i], pv[i]*fv[i]))
    return pv

In [69]:
newClusters = []
for fv in FV:
    print('fv=', fv, '\n')
    P1, HostCluster, number, check = selectCluster(P,fv,betta,ro)
    HostCluster = renewCluster(fv, HostCluster)
    newClusters.append(HostCluster)
    print(P, '\n')
    if(check == False):
        print('renew')
        print(HostCluster)
        print(fv)
        print(np.array(HostCluster))
        print('New Cluster[{0}]={1}\n'.format(number-1, P[number-1]))

fv= [1 0 0 1 1 1 0 0 1] 

False
False
True
3
[array([0, 1, 1, 0, 1, 0, 0, 1, 0]), array([1, 1, 1, 0, 0, 0, 1, 1, 1]), array([1, 0, 0, 1, 1, 0, 0, 0, 0])] 

renew
[1 0 0 1 1 0 0 0 0]
[1 0 0 1 1 1 0 0 1]
[1 0 0 1 1 0 0 0 0]
New Cluster[2]=[1 0 0 1 1 0 0 0 0]

fv= [1 0 0 1 1 1 0 1 1] 

False
False
False
3
[array([0, 1, 1, 0, 1, 0, 0, 1, 0]), array([1, 1, 1, 0, 0, 0, 1, 1, 1]), array([1, 0, 0, 1, 1, 0, 0, 0, 0])] 

fv= [1 1 1 1 1 1 0 0 1] 

False
False
False
3
[array([0, 1, 1, 0, 1, 0, 0, 1, 0]), array([1, 1, 1, 0, 0, 0, 1, 1, 1]), array([1, 0, 0, 1, 1, 0, 0, 0, 0])] 



In [70]:
### Результат ###
for propVect in newClusters:
    print(propVect, '\n')

[1 0 0 1 1 0 0 0 0] 

[1 0 0 1 1 1 0 1 1] 

[1 1 1 1 1 1 0 0 1] 

